### ISSUE TITLE
should we use the correlation or covariance matrix of mvn 

### ISSUE THREAD

**Issue by iskode** [zhanxw/libMvtnorm#1]
Hello Mr Xiaowei , 
I have come across this project that's exactly what I'm looking for. But I(ve a few questions.
For the normal distribution normally, we have a covariance matrix namely Sigma in the for formula. But the parameter indicates correlation Matrix. 
Therefore should I compute the correlation matrix for my normal distribution and use it to call the pmvnorm_P function or use directly the covariance matrix?
I want also to compute the cdf of a non-central normal, I think I just have to shift my normal distribution:
if X ~ N( (2, 3, 5), Cov3x3) then Y = X - (2, 3, 5)  ~ N( (0, 0, 0), Cov3x3)
and if upper = x then for Y upper will be y = x-(2, 3, 5).
Then I can call safely pmvnorm_P function with Y and the new upper y.
I want just to be sure that this is correct. So if not please tell how to correct it and obtain a non central normal cdf.
Lastly (Excuse me for being too long),  How can I do it for a multivariate Student T distribution? Because when I look into the code I saw a nu parameter that recall me the student t law. So are you treating here the normal dist as a particular case of student t? if so then I can use this internal function
mvtdst_ to get the multivariate student t distribution

**Comment by zhanxw** [comment]
Hello,


You're right that you need to put correlation matrix instead of covariance matrix.

I don't understand much about non-central normal, but I guess you can refer to some textbook and transform it to a normal distribution centered at zero.

I am sorry that this library has not consider t-distribution. 
I don't have time to support that now, but happy to incorporate pull-requests.
